<template>
  <div class="pa-5 animated"   >
      <LinearLayout ref="cardInfo" :background-tint="themes[selectedTheme].card" rounded-corners="20" pa="8"
                    :class="{'slide-right':slide}"
                    style="min-height:200px" :style="modifier.shadow(0,20,30,themes[selectedTheme].accent,HexAA.P40)" >
        <LinearLayout horizontal-orientation>
          <TextView text="What's the meaning?" transform="capitalize" size="12" :color="`#000000${HexAA.P50}`"/>
          <v-spacer/>
          <TextView text="Deutsch" transform="capitalize" size="12" :color="`#000000${HexAA.P50}`"/>
        </LinearLayout>
        <TextView :text="`WonderBarWonderBarbar`" bold size="30" class="my-3 text-wrap " style="  overflow: auto;"   />
        <TextView  :text="strings.sample" size="12" line-spacing="2" :class="{'hidden-tip':!showTip}"   />
        <LinearLayout horizontal-orientation  class="justify-end mt-4">
          <v-btn fab :color="themes[selectedTheme].accent" depressed small @click="viewTip()">
            <box-icon type="regular" name="message-square-error" color="black"  />
          </v-btn>
        </LinearLayout>
      </LinearLayout>

    <div class="mt-15">
      <LinearLayout horizontal-orientation class="align-center">
        <TextView text="Your Answer" bold  :color="colors.primaryText" class="ml-2 my-2 mb-2" size="20"/>
        <box-icon type="regular" name="message-square-edit" class="mx-3" :color="colors.primaryText" />
      </LinearLayout>
      <v-text-field mt-6 outlined style="border-radius: 15px"
                    :dark="isDark"
                    x-large
                    :color="colors.primaryText"/>
    </div>
    <v-flex style="bottom:0;left:0; position: fixed; width: 100%;">
      <v-btn :color="themes[selectedTheme].accent"  block depressed x-large style="border-radius: 15px" class="mr-5" @click="restartAnimation()">
        <TextView text="Submit" caps bold color="black"/>
      </v-btn>
    </v-flex>
  </div>
</template>

<script lang="ts">
import Vue from "vue"
import Component from "vue-class-component";
import TextView from "@/utils/UI/TextView/TextView.vue";
import Constants from '@/values/Constants';
import {ColorType,HexAA} from "@/values/Colors";
import {LanguageType} from "@/values/Strings";
import LinearLayout from "@/utils/UI/LinearLayout/LinearLayout.vue";
import Modifier from "@/values/Modifier";
import Utils from "@/utils/Utils";



@Component({
  components: {LinearLayout, TextView}
})
export default class PlayView extends Vue {
  //VARIABLES DECLARATION HERE
  public modifier = Modifier
  public HexAA = HexAA
  public themes = this.colors.playViewThemes as Array<{card:string,accent:string}>
  public selectedTheme:number = 5
  public slide = false
  public showTip = false


  /**
   COMPUTED PROPERTIES HERE (getter and Setters)
   **/

  get colors():ColorType {
    return this.$store.getters.colors;
  }

  get strings():LanguageType {
    return this.$store.getters.strings;
  }
  get isDark():boolean {
    return this.$store.getters.isDark;
  }

  viewTip():void {
    this.showTip = !this.showTip
    setTimeout(() =>{
      this.showTip = false
    },5000)
  }
  restartAnimation():void{
    this.selectedTheme = Utils.getRandomInt(this.themes.length)
     this.slide = true
      setTimeout(()=>{
       this.slide = false

      },300)

  }
  /**
   Life-Hook
   **/
  mounted():void {

    this.restartAnimation()
  }

  /** Methods & watchers
   //@Watch('trigger')
   //onPropertyChanged(flag:boolean,oldFlag:boolean){}
   */


}
</script>

<style scoped lang="scss">

  .animated{

    .slide-right {
      -webkit-animation: hidden-tip 0.15s ease-in-out;
      animation: hidden-tip 0.15s ease-in-out;
    }
    .cardInfo{
      transition: all 0.12s ease-in-out;
    }
    .hidden-tip{
      overflow: hidden;
      //transform: translateX(-100px);
      height: 0!important;
    }

  }

  @keyframes hidden-tip {
    0% {
      -webkit-transform: translateX(0px);
      transform: translateX(0px);
    }
    100% {
      -webkit-transform: translateX(100%);
      transform: translateX(100%);
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2021-3-30 5:26:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation slide-right
   * ----------------------------------------
   */
  @-webkit-keyframes slide-right {
    0% {
      -webkit-transform: translateX(-200px);
      transform: translateX(-200px);
    }
    100% {
      -webkit-transform: translateX(0px);
      transform: translateX(0px);
    }
  }
  @keyframes slide-right {
    0% {
      -webkit-transform: translateX(100px);
      transform: translateX(100px);
    }
    100% {
      -webkit-transform: translateX(0px);
      transform: translateX(0px);
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2021-3-30 5:59:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
   * ----------------------------------------
   * animation scale-up-hor-center
   * ----------------------------------------
   */
  @-webkit-keyframes scale-up-hor-center {
    0% {
      -webkit-transform: scaleX(0.4);
      transform: scaleX(0.4);
    }
    100% {
      -webkit-transform: scaleX(1);
      transform: scaleX(1);
    }
  }
  @keyframes scale-up-hor-center {
    0% {
      -webkit-transform: scaleX(0.4);
      transform: scaleX(0.4);
    }
    100% {
      -webkit-transform: scaleX(1);
      transform: scaleX(1);
    }
  }



</style>